#!/usr/bin/env bash
set -eu

echo "🔵 pre_build"
source hooks/.config

echo "✅ Register qemu-*-static for all supported processors except current"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

docker run --rm --privileged multiarch/qemu-user-static:register --reset -p yes

echo "✅#################  start buildx tasks  ##################"
docker buildx ls
echo "✅#################  Create new buildx builder  ##################"
docker buildx create --name mybuilder
echo "✅#################  Use new buildx builder  ##################"
docker buildx use mybuilder
echo "✅#################  Inspect buildx builder  ##################"
docker buildx inspect --bootstrap
echo "✅################# done with pre_build  ##################"
