#!/usr/bin/env bash
set -eu

echo "🔵 start pre_build"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
source hooks/.config

echo "✅ Register qemu-*-static for all supported processors except current"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

echo "check2: ls -la /proc/sys/fs/binfmt_misc"
ls -la /proc/sys/fs/binfmt_misc
echo "now running: docker run --rm --privileged aptman/qus -s -- -p arm"

#docker run --rm --privileged multiarch/qemu-user-static --reset
#docker run --rm --privileged aptman/qus -s -- -p arm

echo "check3: ls -la /proc/sys/fs/binfmt_misc"
ls -la /proc/sys/fs/binfmt_misc

echo "✅#################  start buildx tasks  ##################"
docker buildx ls
echo "✅#################  Create new buildx builder  ##################"
docker buildx create --name mybuilder
echo "✅#################  Use new buildx builder  ##################"
docker buildx use mybuilder
echo "✅#################  Inspect buildx builder  ##################"
docker buildx inspect --bootstrap
echo "✅################# done with pre_build  ##################"
echo "🔵 end pre_build"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
